### ISSUE TITLE
emacs-head@28 --with-cocoa --with-native-comp fails on startup

### ISSUE THREAD

**Issue by mariusk** [daviderestivo/homebrew-emacs-head#115]
I recently tried to upgrade emacs and it now fails on startup with the following error message:

`~ /usr/local/opt/emacs-head@28/bin/emacs
emacs: can't find function "F6d656e752d6261722d7570646174652d62756666657273_menu_bar_update_buffers_0" in compilation unit /usr/local/Cellar/emacs-head@28/28.0.50_1/libexec/emacs/28.0.50/x86_64-apple-darwin20.6.0/../../../../bin/../lib/emacs/28.0.50/native-lisp/28.0.50-50ea073b/preloaded/menu-bar-4f46ea94-7781c24c.eln
`

Building without `--with-native-comp` seems to work fine. Native compilation has worked fine earlier, so seems like something recent.

**Comment by daviderestivo** [comment]
@mariusk have you tried to uninstall it and install it once again?

**Comment by daviderestivo** [comment]
Lemme me have a look ...

**Comment by daviderestivo** [comment]
Fixed in here: https://github.com/daviderestivo/homebrew-emacs-head/pull/116.
Please check and lemme know if I can close this issue.

**Comment by mariusk** [comment]
Checked now, still the same error after building and running at my end unfortunately.

**Comment by mariusk** [comment]
Xcode 13 beta 2 from June 24th require Monterey, so could not be installed. So I installed 12.5.1 from June 20th. Then rebuilt and tested. Same error still, no difference from before.

**Comment by daviderestivo** [comment]
Can you please provide me with the output of:

```
otool -L /usr/local/Cellar/emacs-head@28/28.0.50_1/libexec/emacs/28.0.50/x86_64-apple-darwin20.6.0/../../../../bin/../lib/emacs/28.0.50/native-lisp/28.0.50-50ea073b/preloaded/menu-bar-4f46ea94-7781c24c.eln
```

**Comment by mariusk** [comment]
Here's the result:
```
~ otool -L /usr/local/Cellar/emacs-head@28/28.0.50_1/libexec/emacs/28.0.50/x86_64-apple-darwin20.6.0/../../../../bin/../lib/emacs/28.0.50/native-lisp/28.0.50-50ea073b/preloaded/menu-bar-4f46ea94-7781c24c.eln
/usr/local/Cellar/emacs-head@28/28.0.50_1/libexec/emacs/28.0.50/x86_64-apple-darwin20.6.0/../../../../bin/../lib/emacs/28.0.50/native-lisp/28.0.50-50ea073b/preloaded/menu-bar-4f46ea94-7781c24c.eln:
	/usr/local/opt/emacs-head@28/lib/emacs/28.0.50/native-lisp/28.0.50-50ea073b/preloaded/fake.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/usr/local/lib/gcc/11/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by daviderestivo** [comment]
Can you please try to uninstall and re-install from the scratch?

**Comment by mariusk** [comment]
I've tried installing from scratch as well (after `brew uninstall`), makes no difference. The exact options I pass are:
```
brew install emacs-head@28 --with-cocoa --with-native-comp
```

**Comment by mariusk** [comment]
I also tried on another computer at work (iMac 2019), everything seems to work fine there. Will try again on the machine where it does not work later and report back. Weird stuff.

**Comment by daviderestivo** [comment]
Can you please install it once again with --verbose and pass me the logs:

`brew install --verbose emacs-head@28 --with-cocoa --with-native-comp`

Thanks

**Comment by mariusk** [comment]
I tried another clean install on the computer where it failed earlier, and now it works here as well. My guess is that something changed upstream that may have fixed it? So "problem solved" I guess, except I have no idea what solved it. Thanks anyway.

**Comment by mariusk** [comment]
Could be this fix, not sure: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49271

**Comment by daviderestivo** [comment]
> Could be this fix, not sure: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49271

Yes. Good catch. I think this was exactly the issue.
